# Generated by Django 4.2.6 on 2023-10-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0002_alter_event_event_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_comment',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
