# Generated by Django 4.2.6 on 2023-10-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0003_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
