# Generated by Django 4.2.6 on 2023-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0003_alter_event_event_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
