# Generated by Django 4.2.6 on 2023-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0004_alter_eventdate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='date',
            field=models.DateField(),
        ),
    ]
