# Generated by Django 4.2.6 on 2023-10-09 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling_app', '0006_eventparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events_attending', through='scheduling_app.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='is_attending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='available_dates',
            field=models.ManyToManyField(blank=True, related_name='participants_available_dates', to='scheduling_app.eventdate'),
        ),
    ]
