# Generated by Django 4.2.6 on 2023-10-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
