# Generated by Django 4.2.6 on 2023-10-09 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling_app', '0007_event_participants_eventparticipant_is_attending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='events_attending', through='scheduling_app.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
