# Generated by Django 4.2.6 on 2023-10-09 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling_app', '0009_remove_event_participants_delete_eventparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attending', models.BooleanField(default=False)),
                ('available_dates', models.ManyToManyField(blank=True, related_name='participants_available_dates', to='scheduling_app.eventdate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events_attending', through='scheduling_app.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
