# Generated by Django 4.2.6 on 2023-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0010_eventparticipant_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_dates',
            field=models.ManyToManyField(related_name='available_participants', to='scheduling_app.eventdate'),
        ),
    ]
