# Generated by Django 4.2.6 on 2023-10-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0010_delete_eventdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='unique_code',
            new_name='event_code',
        ),
    ]
