# Generated by Django 4.2.6 on 2023-10-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0011_userprofile_available_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='available_dates',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
