# Generated by Django 4.2.6 on 2023-10-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0012_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_dates', models.ManyToManyField(related_name='participants', to='scheduling_app.eventdate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_app.event')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_app.userprofile')),
            ],
        ),
    ]
